### ISSUE TITLE
Feedback01

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SSSMobileApp#1]

**Comment by adilshehbaz** [comment]
1)	If the system is left unattended automatic logout should be after 1 hour. **RFR**
3)	The system is giving a message of unknown problem,PFA screenshot herewith. **RFR**
4)	Please standardize error text instead of “Oops something went wrong” **RFR**
6)	In “Tsm2” please add Cc & Bcc option. **RFR**
7)	In “Tsm2” Note should have all editing options. **RFR**

**Comment by adilshehbaz** [comment]
5)	PFA “Tsm2”. In “To” address bar instead of email addresses we want entity to be shown like all customers,vendors etc and after clicking there name the person’s of that particular organisation should be shown along with email addresses.  **RFR**

**Comment by serviceproviderpk** [comment]
1,2,3,4 &5 are ready for testing.

**Comment by Technotsm** [comment]
no 5.has not been implemented. in "Tsm2" In "To" we want entities to be shown i-e all customers & vendors but not their individuals.one they have been shown than the individuals of only that company must be shown.If there is any confusion plz feel free to call me

**Comment by Technotsm** [comment]
in this URL "http://tsm.technobiz.com.pk/BusinessEntity/Index" there should be option of sorting out, e-g if i just want to sort out all customers or vendors & once sorted our must be shown alphabetically.

**Comment by adilshehbaz** [comment]
in this URL "http://tsm.technobiz.com.pk/BusinessEntity/Index" there should be option of sorting out, e-g if i just want to sort out all customers or vendors & once sorted our must be shown alphabetically.
**Fixed**
